### ISSUE TITLE
Error when proposal's title contains quotes

### ISSUE THREAD

**Issue by pabluk** [sre-paris/meetups#16]
The workflow [Parse Issues](https://github.com/sre-paris/meetups/blob/9f8b0262db2352801c43513d55792943097aeccb/.github/workflows/content.yml) fails with the following payload:
```
---
title: "A review of "How Complex Systems Fail""
date: 2021-07-19T20:11:32Z
github_username: pabluk
twitter_username: pabluk
---
__author name__: Pablo Seminario (@pabluk)

__author bio__: SRE at @Resiliencecare 

__expected time__ :

- [ ] lightning talk (~ 5 min)
- [x] 15 min

__language__:

- [x] :fr:
- [x] :uk:

__abstract__: A review of the well-known treatise [How Complex Systems Fail](https://how.complexsystems.fail/) with some real-world examples to have a better understanding of incidents and improve our post-incident reviews.
```
Here are more details about the error https://github.com/sre-paris/meetups/runs/3107819100

**Comment by tormath1** [comment]
Fun ! I suggest to remove the quotes `cfp/2021-07-19-a-review-of-"how-complex-systems-fail".md` would become `cfp/2021-07-19-a-review-of-how-complex-systems-fail.md` and a test case. What do you think ?

**Comment by pabluk** [comment]
> Fun ! I suggest to remove the quotes `cfp/2021-07-19-a-review-of-"how-complex-systems-fail".md` would become `cfp/2021-07-19-a-review-of-how-complex-systems-fail.md` and a test case. What do you think ?

Yeah! totally agree, that will do the job. By the way I've done something like that here [main/scripts/create-content/main.py](https://github.com/sre-paris/reliability.re/blob/main/scripts/create-content/main.py#L11-L30) but I'm not sure if it's a good example :sweat_smile:

**Comment by tormath1** [comment]
Yeah, the slugify has been [backported](https://github.com/sre-paris/meetups/blob/39ee010755a0fbcb74ddcf62d4b3236764b5e665/scripts/create-content/main.py#L12-L30) but it does not hold the `"` case. :thinking:

**Comment by pabluk** [comment]
> Yeah, the slugify has been [backported](https://github.com/sre-paris/meetups/blob/39ee010755a0fbcb74ddcf62d4b3236764b5e665/scripts/create-content/main.py#L12-L30) but it does not hold the `"` case. :thinking: 

oh yes, I forgot that, I'm getting old! :older_man:
